movieapp/urls.py
from django.urls import path,include

from . import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('add/',views.add,name='add'),
    path('movie/<int:movie_id>/',views.detail, name='detail'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import movie
class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import movieform
from .models import movie
# Create your views here.
def index(request):
    movies = movie.objects.all()
    context={
        'movie_list':movies
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movies=movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movies})

def add(request):
    if request.method=='POST':
        name=request.POST.get('name' , )
        desc = request.POST.get('desc' , )
        year = request.POST.get('year' , )
        img = request.FILES['img']
        movies=movie(name=name,desc=desc,year=year,img=img)
        movies.save()
    return render(request,'add.html')

def update(request,id):
    movies=movie.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES,instance=movies)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form, 'movies':movies})

def delete(request,id):
    if request.method=='POST':
        movies=movie.objects.get(id=id)
        movies.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"><br>
    <input type="text" name="desc" placeholder="Enter Description"><br>
    <input type="number" name="year" placeholder="Enter movie year"><br>
    <label>add image</label><input type="file" name="img"><br>
    <input type="submit">
</form>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this movie?
    <input type="submit">
</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300"><br>
        </div>
         <div class="col-md-6">
            <h3 style="color:green">{{movie.name}}</h3>
             <h5>{{movie.desc}}</h5>
             <h6>{{movie.year}}</h6>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem; height: 30rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap"  height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
<!--<img src="{{i.img.url}}" width="100" height="100">-->
<!--&lt;!&ndash;<a href="movie/{{i.id}}">{{i.name}}<br>&ndash;&gt;-->
<!--<a href="{% url 'movieapp:detail' i.id %}">{{i.name}}</a><br>-->